// @generated by protoc-gen-config 0.0.1 with parameter "target=ts"
// @generated from file tech/atls/auth/v1/auth.service.proto (package tech.atls.auth.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import path from 'node:path'

const dirname = path.dirname(new URL(import.meta.url).pathname)

export const packageName = 'tech.atls.auth.v1'

export const serviceName = 'AuthService'

export const servicePath = path.join(dirname, '../tech/atls/auth/v1/auth.service.proto')

export const includeDirs = [path.join(dirname, '../')]
