compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: true

globalFolder: ../.yarn/berry

packageExtensions:
  '@nestjs/core@10.4.7':
    dependencies:
      '@nestjs/websockets': '10.4.7'
  '@nestjs/websockets@10.4.7':
    dependencies:
      '@nestjs/platform-socket.io': '10.4.7'
  '@nestjs/microservices@10.4.7':
    dependencies:
      '@nestjs/websockets': '10.4.7'
      'kafkajs': '2.2.4'
      '@grpc/proto-loader': '0.7.13'
      'ioredis': '5.4.1'
      'amqplib': '0.10.4'
      'amqp-connection-manager': '4.1.14'
  '@atls/nestjs-grpc-reflection@0.0.10':
    dependencies:
      'long': '5.2.3'

pnpEnableEsmLoader: true

preferReuse: true

yarnPath: .yarn/releases/yarn.cjs
