packageExtensions:
  '@apollo/gateway@*':
    dependencies:
      node-fetch: '*'
  '@donews/nestjs-async-hooks@*':
    dependencies:
      express: '*'
  '@atls/nestjs-grpc-http-proxy@*':
    dependencies:
      express: '*'
  '@atls/nestjs-grpc-reflection@*':
    dependencies:
      long: '*'
      protobufjs: '*'
  '@atls/react-kratos-forms@*':
    dependencies:
      '@ory/kratos-client': 0.5.4-alpha.1
  '@nestjs/common@*':
    dependencies:
      '@grpc/proto-loader': '*'
      '@nestjs/platform-express': '*'
      cache-manager: '*'
      class-transformer: '*'
      class-validator: '*'
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/microservices': '*'
      '@nestjs/platform-express': '*'
      '@nestjs/websockets': '*'
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/event-emitter@*':
    dependencies:
      '@nestjs/core': '*'
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/graphql@*':
    dependencies:
      '@apollo/federation': '*'
      apollo-server-express: '*'
      apollo-server-fastify: '*'
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/mapped-types@*':
    dependencies:
      class-transformer: '*'
      class-validator: '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/proto-loader': '*'
      '@nestjs/websockets': '*'
      grpc: '*'
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/testing@*':
    dependencies:
      '@nestjs/microservices': '*'
      '@nestjs/platform-express': '*'
  '@nestjs/typeorm@*':
    dependencies:
      rxjs: '*'
  apollo-server-fastify@*:
    dependencies:
      fast-json-stringify: '*'
  debug@*:
    dependencies:
      supports-color: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  fast-json-stringify@*:
    dependencies:
      long: '*'
  fastify-plugin@*:
    dependencies:
      fastify: '*'
  follow-redirects@*:
    dependencies:
      debug: '*'
  hash-stream-validation@*:
    dependencies:
      fast-crc32c: '*'
  pg-cursor@*:
    dependencies:
      pg: '*'
  pino@*:
    dependencies:
      pino-pretty: '*'
  promise-inflight@*:
    dependencies:
      bluebird: '*'
  retry-request@*:
    dependencies:
      request: '*'
  typeorm@*:
    dependencies:
      pg: '*'
      pg-query-stream: '*'
      sqlite3: '*'
  ws@*:
    dependencies:
      bufferutil: '*'
      utf-8-validate: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - .yarn/plugins/@atls/plugin-essentials.cjs

yarnPath: .yarn/releases/yarn-3.0.0-rc.5.cjs
