packageExtensions:
  '@atls/nestjs-grpc-http-proxy@*':
    dependencies:
      express: '*'
  '@atls/nestjs-grpc-reflection@*':
    dependencies:
      long: '*'
      protobufjs: '*'
  '@atls/typeorm-logger@*':
    dependencies:
      typeorm: '*'
  '@grpc/grpc-js@*':
    dependencies:
      '@types/long': '*'
  '@nestjs/common@*':
    dependencies:
      '@grpc/proto-loader': '*'
      cache-manager: '*'
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/platform-express': '*'
      '@nestjs/websockets': '*'
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/cqrs@*':
    dependencies:
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/grpc-js': '*'
      '@grpc/proto-loader': '*'
      '@nestjs/websockets': '*'
      kafkajs: '*'
  '@nestjs/typeorm@*':
    dependencies:
      rxjs: '*'
  '@nestjs/websockets@*':
    dependencies:
      '@nestjs/platform-socket.io': '*'
  debug@*:
    dependencies:
      supports-color: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  follow-redirects@*:
    dependencies:
      debug: '*'
  pg-cursor@*:
    dependencies:
      pg: '*'
  pino@*:
    dependencies:
      pino-pretty: '*'
  typeorm@*:
    dependencies:
      pg: '*'
      pg-query-stream: '*'
      sqlite3: '*'
  ws@*:
    dependencies:
      bufferutil: '*'
      utf-8-validate: '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20220304.hash-6afc8ff.cjs
