compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

packageExtensions:
  '@atls/nestjs-grpc-http-proxy@*':
    dependencies:
      express: '*'
  '@atls/nestjs-grpc-reflection@*':
    dependencies:
      long: '*'
  '@atls/typeorm-logger@*':
    dependencies:
      typeorm: '*'
  '@grpc/grpc-js@*':
    dependencies:
      '@types/long': '*'
  '@nestjs/common@*':
    dependencies:
      '@grpc/proto-loader': '*'
      cache-manager: '*'
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/platform-express': '*'
      '@nestjs/websockets': '*'
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/cqrs@*':
    dependencies:
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/grpc-js': '*'
      '@grpc/proto-loader': '*'
      '@nestjs/websockets': '*'
      kafkajs: '*'
  '@nestjs/typeorm@*':
    dependencies:
      rxjs: '*'
  '@nestjs/websockets@*':
    dependencies:
      '@nestjs/platform-socket.io': '*'
  debug@*:
    dependencies:
      supports-color: '*'
  pg-cursor@*:
    dependencies:
      pg: '*'
  pino@*:
    dependencies:
      pino-pretty: '*'
  typeorm@*:
    dependencies:
      pg: '*'
      pg-query-stream: '*'
      sqlite3: '*'
  ws@*:
    dependencies:
      bufferutil: '*'
      utf-8-validate: '*'

preferReuse: true

yarnPath: .yarn/releases/yarn-remote.cjs
