compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: true

globalFolder: ../.yarn/berry

pnpEnableEsmLoader: true

preferReuse: true

yarnPath: .yarn/releases/yarn-remote.mjs

packageExtensions:
  '@atls/nestjs-gateway@*':
    peerDependencies:
      ws: '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/platform-express': '*'
      '@nestjs/websockets': '*'
  '@nestjs/websockets@*':
    dependencies:
      '@nestjs/platform-socket.io': '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/proto-loader': '*'
      '@nestjs/websockets': '*'
      'kafkajs': '*'
      '@grpc/grpc-js': '*'
      'ioredis': '*'
      'amqplib': '*'
      'amqp-connection-manager': '*'
  '@nestjs/platform-fastify@*':
    dependencies:
      '@fastify/static': '*'
      '@fastify/view': '*'
  '@mikro-orm/knex@*':
    dependencies:
      'mariadb': '*'
      'libsql': '*'
      '@mikro-orm/entity-generator': '*'
      '@mikro-orm/migrations': '*'
  'knex@*':
    dependencies:
      'pg': '8.12.0'
      'pg-query-stream': '4.6.0'
