compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: true

globalFolder: ../.yarn/berry

npmRegistryServer: 'https://registry.npmjs.org'

npmScopes:
  atls:
    npmRegistryServer: 'https://registry.npmjs.org'

packageExtensions:
  '@mikro-orm/core@7.2.5':
    dependencies:
      tinyglobby: 0.2.17
  '@graphql-mesh/types@0.45.2':
    dependencies:
      '@graphql-mesh/store': 0.1.19
  '@graphql-mesh/store@0.1.19':
    dependencies:
      '@graphql-mesh/types': 0.45.2
  '@mikro-orm/postgresql@7.2.5':
    dependencies:
      '@types/pg': 8.20.0
  '@fastify/cors@11.3.0':
    dependencies:
      fastify: 5.11.3
  '@atls/nestjs-gateway@*':
    peerDependencies:
      ws: '*'
  '@nestjs/apollo@*':
    dependencies:
      '@apollo/gateway': '*'
      '@apollo/subgraph': '*'
      '@as-integrations/fastify': '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/platform-express': '*'
      '@nestjs/websockets': '*'
  '@nestjs/graphql@*':
    dependencies:
      '@apollo/subgraph': '*'
      ts-morph: '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/grpc-js': '*'
      '@grpc/proto-loader': '*'
      '@nestjs/websockets': '*'
      amqp-connection-manager: '*'
      amqplib: '*'
      ioredis: '*'
      kafkajs: '*'
  '@nestjs/platform-fastify@*':
    dependencies:
      '@fastify/static': '*'
      '@fastify/view': '*'
  '@nestjs/platform-express@10.4.15':
    dependencies:
      '@types/express': 4.17.21
  '@nestjs/websockets@*':
    dependencies:
      '@nestjs/platform-socket.io': '*'
  'fetchache@0.1.1':
    dependencies:
      '@types/http-cache-semantics': 4.2.0
  'subscriptions-transport-ws@0.11.0':
    dependencies:
      '@types/ws': 8.5.13
  'subscriptions-transport-ws@0.9.19':
    dependencies:
      '@types/ws': 7.4.7

pnpEnableEsmLoader: true

preferReuse: true

yarnPath: .yarn/releases/yarn.js
