compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: true

globalFolder: ../.yarn/berry

pnpEnableEsmLoader: true

preferReuse: true

yarnPath: .yarn/releases/yarn-remote.mjs

packageExtensions:
  '@atls/nestjs-grpc-http-proxy@*':
    dependencies:
      express: '*'
  '@atls/nestjs-grpc-reflection@*':
    dependencies:
      long: '*'
  '@atls/nestjs-gateway@*':
    peerDependencies:
      ws: '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/platform-express': '*'
      '@nestjs/websockets': '*'
  '@nestjs/websockets@*':
    dependencies:
      '@nestjs/platform-socket.io': '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/proto-loader': '*'
      '@nestjs/websockets': '*'
      'kafkajs': '*'
      '@grpc/grpc-js': '*'
      'ioredis': '*'
      'amqplib': '*'
      'amqp-connection-manager': '*'
  '@nestjs/platform-fastify@*':
    dependencies:
      '@fastify/static': '*'
      '@fastify/view': '*'
  '@graphql-tools/graphql-tag-pluck@*':
    dependencies:
      '@vue/compiler-sfc': '3.3.8'
      svelte2tsx: '0.7.5'
      svelte: '4.2.12'
  '@mikro-orm/knex@*':
    dependencies:
      'mariadb': '*'
      'libsql': '*'
  'knex@*':
    dependencies:
      'pg': '8.12.0'
      'pg-query-stream': '4.6.0'
