compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: true

globalFolder: ../.yarn/berry

npmRegistryServer: 'https://registry.npmjs.org'

npmScopes:
  atls:
    npmRegistryServer: 'https://registry.npmjs.org'

packageExtensions:
  '@atls/nestjs-gateway@*':
    peerDependencies:
      ws: '*'
  '@mikro-orm/knex@*':
    dependencies:
      '@mikro-orm/entity-generator': '*'
      '@mikro-orm/migrations': '*'
      libsql: '*'
      mariadb: '*'
  '@nestjs/apollo@*':
    dependencies:
      '@apollo/gateway': '*'
      '@apollo/subgraph': '*'
      '@as-integrations/fastify': '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/platform-express': '*'
      '@nestjs/websockets': '*'
  '@nestjs/graphql@*':
    dependencies:
      '@apollo/subgraph': '*'
      ts-morph: '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/grpc-js': '*'
      '@grpc/proto-loader': '*'
      '@nestjs/websockets': '*'
      amqp-connection-manager: '*'
      amqplib: '*'
      ioredis: '*'
      kafkajs: '*'
  '@nestjs/platform-fastify@*':
    dependencies:
      '@fastify/static': '*'
      '@fastify/view': '*'
  '@nestjs/websockets@*':
    dependencies:
      '@nestjs/platform-socket.io': '*'
  knex@*:
    dependencies:
      pg: 8.12.0
      pg-query-stream: 4.6.0

pnpEnableEsmLoader: true

preferReuse: true

yarnPath: .yarn/releases/yarn-remote.mjs
