volumes:
  yarn:

services:
  yarn:
    image: node:22
    working_dir: /workspace
    volumes:
      - yarn:/.yarn/berry
      - ./:/workspace
    entrypoint: yarn

  db:
    image: bitnami/postgresql
    env_file:
      - .config/.env
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U postgres -d firstfood_core
      interval: 30s
      timeout: 10s
      retries: 3
      start_interval: 3s
      start_period: 5s

  gcs:
    image: fsouza/fake-gcs-server
    command: -scheme http -external-url http://localhost:4443
    volumes:
      - .data/gcs:/storage
    ports:
      - 4443:4443

  gateway:
    image: node:22
    working_dir: /workspace
    volumes:
      - yarn:/.yarn/berry
      - ./:/workspace
    entrypoint: yarn workspace @gateway/public-gateway-entrypoint dev
    environment:
      - FILES_SERVICE_URL=files:50051
    env_file:
      - .config/.env
    ports:
      - '3000:3000'
    depends_on:
      - yarn
      - files

  files:
    image: node:22
    working_dir: /workspace
    volumes:
      - yarn:/.yarn/berry
      - ./:/workspace
    entrypoint: yarn workspace @files/service-entrypoint dev
    env_file:
      - .config/.env
