name: Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'

jobs:
  release:
    uses: atls/shared/.github/workflows/pack-image.yaml@master
    permissions: write-all
    with:
      registryURL: ghcr.io
      registryUser: ${{ github.repository_owner }}
      project: ${{ github.repository_owner }}
    secrets:
      registryKey: ${{ secrets.GITHUB_TOKEN }}
